<?php

namespace Flying\ObjectBuilder\Exception;

/**
 * Base exception class for all exceptions generated by object builder and its handlers
 */
abstract class ObjectBuilderException extends \RuntimeException implements ObjectBuilderExceptionInterface
{

}
